# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'AdaptiveHapticsExample' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    # Workaround for Xcode 26 beta: UIUtilities is now a SubFramework.
    app_target = installer.pods_project.targets.find { |t| t.name == 'AdaptiveHapticsExample' }
    if app_target
      app_target.build_configurations.each do |config|
        subframeworks_path = '$(DEVELOPER_DIR)/Platforms/$(PLATFORM_NAME).platform/Developer/SDKs/$(SDK_NAME)/System/Library/SubFrameworks'
        config.build_settings['FRAMEWORK_SEARCH_PATHS'] ||= ['$(inherited)']
        config.build_settings['FRAMEWORK_SEARCH_PATHS'] << subframeworks_path
        config.build_settings['OTHER_LDFLAGS'] ||= ['$(inherited)']
        config.build_settings['OTHER_LDFLAGS'] << '-Wl,-weak_framework,UIUtilities'
        config.build_settings['OTHER_LDFLAGS'] << '-Wl,-weak_framework,SwiftUICore'
      end
    end
  end
end
